### ISSUE TITLE
Acknowledge NFT artist

### ISSUE THREAD

**Issue by rootulp** [IndexCoop/coop-tax#17]
### Motivation

> They were re-purposed from POAP design and look nice! Should probably give credit back to the artist on the site.

From @edwardk in Discord

### To do
- [x] Get approval from NFT artist prior to proceeding
- [x] Add an acknowledgement on https://coop.tax/ for their work

**Comment by rootulp** [comment]
Sample copy for acknowledgement

> Thanks to [Guada](https://twitter.com/GuadaTonti) and the [POAP](https://twitter.com/poapxyz) team for their creative work on these owl NFTs.

**Comment by 0xModene** [comment]
I've just put this through alongside another update
